AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda para processar vídeos com FFmpeg

Parameters:
  LambdaRoleArn:
    Type: String
    Description: ARN da IAM Role criada via CI/CD

  LayerVersion:
    Type: String
    Description: Versão da Layer FFmpeg

Resources:
  ffmpegprocessvideo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ffmpeg-process-video-hackaton-fiap-2025
      CodeUri: ./src
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      MemorySize: 512
      Timeout: 123
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:fiap-hackaton-2025-ffmpeg-layer-2025layer:${LayerVersion}
      Role: !Ref LambdaRoleArn

Outputs:
  LambdaFunctionName:
    Value: !Ref ffmpegprocessvideo
  LayerVersion:
    Value: !Ref LayerVersion