AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda para processar vídeos com FFmpeg

Parameters:
  LambdaRoleArn:
    Type: String
    Description: ARN da IAM Role criada via CI/CD

Resources:
  ffmpegprocessvideo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role: !Ref LambdaRoleArn
      MemorySize: 512
      Timeout: 123
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:fiap-hackaton-2025-ffmpeg-layer-2025layer:1
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-east-2:843985541959:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:us-east-2:843985541959:log-group:/aws/lambda/process-video:*
            - Effect: Allow
              Action:
                - s3:*
                - s3-object-lambda:*
              Resource: '*'